// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8e20U8ASo_zbvA-f3ZP_wePDYhXHlUl8',
    appId: '1:672978419381:web:602be7eade66b916dc88fc',
    messagingSenderId: '672978419381',
    projectId: 'noteverse-d7eb2',
    authDomain: 'noteverse-d7eb2.firebaseapp.com',
    storageBucket: 'noteverse-d7eb2.firebasestorage.app',
    measurementId: 'G-WXD4B23ZKV',
    databaseURL: 'https://noteverse-d7eb2-default-rtdb.firebaseio.com',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXOROMkWVQY_1ijkIZekwuYReZ2cs1Yac',
    appId: '1:672978419381:android:2c680aa8da686466dc88fc',
    messagingSenderId: '672978419381',
    projectId: 'noteverse-d7eb2',
    storageBucket: 'noteverse-d7eb2.firebasestorage.app',
    databaseURL: 'https://noteverse-d7eb2-default-rtdb.firebaseio.com',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxc8fMOHVmHXlaVzs7qTDMBIfr8j5aMLg',
    appId: '1:672978419381:ios:8594259693f4ea74dc88fc',
    messagingSenderId: '672978419381',
    projectId: 'noteverse-d7eb2',
    storageBucket: 'noteverse-d7eb2.firebasestorage.app',
    iosBundleId: 'com.example.notesSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxc8fMOHVmHXlaVzs7qTDMBIfr8j5aMLg',
    appId: '1:672978419381:ios:8594259693f4ea74dc88fc',
    messagingSenderId: '672978419381',
    projectId: 'noteverse-d7eb2',
    storageBucket: 'noteverse-d7eb2.firebasestorage.app',
    iosBundleId: 'com.example.notesSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8e20U8ASo_zbvA-f3ZP_wePDYhXHlUl8',
    appId: '1:672978419381:web:5facf514ef752233dc88fc',
    messagingSenderId: '672978419381',
    projectId: 'noteverse-d7eb2',
    authDomain: 'noteverse-d7eb2.firebaseapp.com',
    storageBucket: 'noteverse-d7eb2.firebasestorage.app',
    measurementId: 'G-RWN23HJQ8S',
    databaseURL: 'https://noteverse-d7eb2-default-rtdb.firebaseio.com',

  );
}
